---
# OpenRelik role defaults
# Uses official install script from https://github.com/openrelik/openrelik-deploy

openrelik_install_dir: /opt/openrelik
openrelik_api_port: 8710
openrelik_ui_port: 8711
openrelik_workers_enabled: true
openrelik_extra_workers:
  - service: openrelik-worker-clamav
    concurrency: 2
  - service: openrelik-worker-capa
    concurrency: 1
  - service: openrelik-worker-eml
    concurrency: 1
  - service: openrelik-worker-entropy
    concurrency: 1
  - service: openrelik-worker-eztools
    concurrency: 1
  - service: openrelik-worker-exif
    concurrency: 1
  - service: openrelik-worker-regripper
    concurrency: 1
  - service: openrelik-worker-ssdeep
    concurrency: 1
  - service: openrelik-worker-yara
    concurrency: 2
openrelik_worker_registry: ghcr.io/openrelik
openrelik_worker_tag: latest
