---
- name: Provision local host services
  hosts: localhost
  connection: local
  become: yes
  vars:
    common_configure_network: false
    guacamole_tls_enabled: true
    guacamole_tls_self_signed: true

  roles:
    - common       # Base tools + Docker
    - openrelik    # Run OpenRelik on host via Docker
    - guacamole    # Remote access portal
