# Utgard Lab Inventory

[firewall]
utgard-firewall ansible_host=192.168.121.47 ansible_ssh_private_key_file=/home/azureuser/git/utgard/.vagrant/machines/firewall/libvirt/private_key

[remnux]
utgard-remnux ansible_host=192.168.121.233 ansible_ssh_private_key_file=/home/azureuser/git/utgard/.vagrant/machines/remnux/libvirt/private_key

[windows_analysis]
utgard-win ansible_host=192.168.121.239 ansible_user=vagrant ansible_password=vagrant ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5985 ansible_winrm_server_cert_validation=ignore

[lab:children]
firewall
remnux
windows_analysis

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/home/azureuser/git/utgard/.vagrant/machines/remnux/libvirt/private_key
host_public_ip=20.240.216.254

[localhost]
127.0.0.1 ansible_connection=local ansible_python_interpreter=/usr/bin/python3
