# Utgard Lab Inventory

[firewall]
utgard-firewall

[remnux]
utgard-remnux

[lab:children]
firewall
remnux

[all:vars]
ansible_user = vagrant
ansible_ssh_private_key_file = ~/.vagrant.d/insecure_private_key
host_public_ip = 20.240.216.254

[localhost]
127.0.0.1 ansible_connection=local ansible_python_interpreter=/usr/bin/python3
